name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '6.0.x'

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1.2

      - name: Restore Packages
        working-directory: ./Web
        run: nuget restore EdubaseWeb.sln

      - name: Build Solution
        working-directory: ./Web
        run: |
          msbuild.exe EdubaseWeb.sln  /t:Rebuild /p:platform="Any CPU" /p:configuration="Release"

      ## Currently manually specifying the tests to trigger -- unclear if these can be picked up automatically?
      - name: Run Tests
        working-directory: ./Web
        run: |
          vstest.console.exe /Enablecodecoverage .\**Tests.dll

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dotnet-results-${{ env.DOTNET_VERSION }}
          path: ./Web/TestResults
        if: ${{ always() }}

      - shell: powershell
        run: |
          Get-ChildItem -Path ${{ runner.workspace }} -Recurse
        continue-on-error: true

      - shell: powershell
        run: |
          Get-ChildItem -Path ./Web/TestResults -Recurse
        continue-on-error: true

      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: ${{ runner.workspace }}/**/*.cobertura.xml
