name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '5.0.x'

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd ./Web

      - name: Restore Packages
        run: dotnet restore EdubaseWeb.sln

      - name: Build Solution
        run: |
          msbuild.exe EdubaseWeb.sln /p:platform="Any CPU" /p:configuration="Release"
        
      ## Currently manually specifying the tests to trigger -- unclear if these can be picked up automatically?
      - name: Run Tests
        run: |
          vstest.console.exe .\Edubase.CommonUnitTests\bin\Release\Edubase.CommonUnitTests.dll
          vstest.console.exe .\Edubase.DataUnitTests\bin\Release\Edubase.DataUnitTests.dll
          vstest.console.exe .\Edubase.ServicesUnitTests\bin\Release\Edubase.ServicesUnitTests.dll
          vstest.console.exe .\Edubase.Web.ResourcesUnitTests\bin\Release\Edubase.Web.ResourcesUnitTests.dll
          vstest.console.exe .\Edubase.Web.UIUnitTests\bin\Release\Edubase.Web.UIUnitTests.dll


      
